library(ISLR)
library(MASS)
library(corrplot) # We'll use corrplot later on in this example too.
library(dplyr)
library(ggplot2)
library(visreg) # This library will allow us to show multivariate graphs.
library(rgl)
library(knitr)
library(scatterplot3d)
data("Auto")
attach(Auto)
head(Auto)
auto_df=Auto[,-9]
summary(auto_df)
# Plot matrix of all variables.
plot(auto_df, col="navy", main="Matrix Scatterplot")
cor(auto_df)
require(caTools)
# splits the data in the ratio mentioned in SplitRatio. After splitting marks these rows as logical TRUE and the the remaining are marked as logical FALSE
sample = sample.split(auto_df,SplitRatio = 0.80) 
train1 =subset(auto_df,sample ==TRUE) # creates a training dataset named train1 with rows which are marked as TRUE
test1=subset(auto_df, sample==FALSE)
summary(train1)
summary(test1)
fit1<- lm(mpg~., data = train1)
summary(fit1)
cor = cor(test1[1:8])
corrplot(cor, method = "number")
fit2 <- lm(mpg~weight+year+origin,data = train1)
summary(fit2)
fit3 <- lm(log(mpg)~weight+year+origin,data = train1)
summary(fit3)
fit4 <- lm(log(mpg)~log(weight)+year+origin,data = auto_df)
summary(fit4)
plot(fit4,which = 1)
fit5 <- lm(log(mpg)~log(weight)+year,data = auto_df)
summary(fit5)
plot(fit5,which = 1)
#Accuracy
predictions<-predict(fit5, test1)
mse <- mean((test1$mpg - predictions)^2)
print(mse)
sigma(fit5)/mean(test1$mpg)
test1$predicted<- predict(fit5,test1)
actuals_preds <- data.frame(test1$mpg,test1$predicted)
names(actuals_preds)<- c("mpg","predicted")
correlation_accuracy <- cor(actuals_preds)
correlation_accuracy
head(actuals_preds)
actuals_preds$log_mpg <- log(actuals_preds$mpg)
head(actuals_preds)